### ISSUE TITLE
[Golang] Can't use Trie - error: redefinition of

### ISSUE THREAD

**Issue by Freeshnik** [51Degrees/Device-Detection#48] opened 2020-06-10 17:05 UTC
Hello,
in before thank you for greate database.

I have problems with usage Trie module on Golang language:

```
go run StronglyTypedHashTrie.go
In file included from ./../cache.h:31:0,
                 from ./../cache.c:1,
                 from ../../pkg/FiftyOneDegrees/trie/FiftyOneDegreesTrieV3.go:20:
./../threading.h:294:1: error: redefinition of '__fod_sync_bool_compare_and_swap_16'
 __fod_sync_bool_compare_and_swap_16(
 ^
In file included from ./../threading.c:28:0,
                 from ../../pkg/FiftyOneDegrees/trie/FiftyOneDegreesTrieV3.go:19:
./../threading.h:294:1: note: previous definition of '__fod_sync_bool_compare_and_swap_16' was here
 __fod_sync_bool_compare_and_swap_16(
 ^
```
### Steps to Reproduce
* git clone https://github.com/51Degrees/Device-Detection.git
* cd Device-Detection/go
* make hash
* Open StronglyTypedHashTrie.go and specify your .trie file location for dataFile variable. Save file
* go run StronglyTypedHashTrie.go

### Expected and Actual Results
Expected output:
```
Mobile User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X)   AppleWebKit/537.51.2 (KHTML, like Gecko) 'Version/7.0 Mobile/11D167 Safari/9537.53
```
and other user-agents outputs

Actual results:
```
In file included from ./../cache.h:31:0,
                 from ./../cache.c:1,
                 from ../../pkg/FiftyOneDegrees/trie/FiftyOneDegreesTrieV3.go:20:
./../threading.h:294:1: error: redefinition of '__fod_sync_bool_compare_and_swap_16'
 __fod_sync_bool_compare_and_swap_16(
 ^
In file included from ./../threading.c:28:0,
                 from ../../pkg/FiftyOneDegrees/trie/FiftyOneDegreesTrieV3.go:19:
./../threading.h:294:1: note: previous definition of '__fod_sync_bool_compare_and_swap_16' was here
 __fod_sync_bool_compare_and_swap_16(
 ^
```

### Additional info
Data File version: 51Degrees-EnterpriseV3.4.trie
OS: Ubuntu 16.04 (also tried on fresh installed Ubuntu 18.04 on VPS)
go version: go1.14 linux/amd64 (go version go1.14.4 linux/amd64 on VPS)

Thx in advance

P.S. Pattern module works just fine

**Comment by 9mm** [comment] 2020-11-20 16:32
Is anyone going to fix this? It's crap paying $1000 a month for something and libraries don't even work

**Comment by ukali53** [comment] 2020-11-20 17:14
Hi @9mm could you please contact support@51degrees.com so we can discuss the issue that's been raised the trie algorithm?

**Comment by tungntpham** [comment] 2020-11-27 15:00
Hi all,

Many thanks for your patience. We have now made the fix to address the issue. The fix is currently with the branch 
https://github.com/51Degrees/Device-Detection/tree/hotfix/compile-trie

Could you give a try with this branch and let us know if the issue is resolved for you?

Many thanks

**Comment by 9mm** [comment] 2020-11-27 18:41
awesome thanks. This also made me lol

![image](https://user-images.githubusercontent.com/1386207/100477392-0bbf0980-309d-11eb-9a5c-f73cfe4989e9.png)

**Comment by jwrosewell** [comment] 2020-11-27 18:57
Thanks. Ow dear. We'll need a spell checker warning plugin. Know of any? :-)

**Comment by 9mm** [comment] 2020-11-27 20:37
> Thanks. Ow dear. We'll need a spell checker warning plugin. Know of any? :-)

haha not sure of one, I just use `:set spell` in vim 😎

**Comment by Steve51D** [comment] 2021-02-11 12:56
Closing this as resolved. If you still have any issues, please let us know.

**Closed by Steve51D** 2021-02-11 12:56 UTC

**Comment by stcharitak** [comment] 2021-02-12 16:04
I try this branch https://github.com/51Degrees/Device-Detection/tree/hotfix/compile-trie and I keep on getting the same error.
Has anyone made it work?

**Comment by stcharitak** [comment] 2021-02-15 11:13
I was able to make hash algorithm work with the above branch https://github.com/51Degrees/Device-Detection/tree/hotfix/compile-trie. However, I still get the redefined error if I use both algorithms in my program. I want to be able to do:

```	patternProvider := FiftyOneDegreesPatternV3.NewProvider(patternFile)
	hashProvider := FiftyOneDegreesHashV3.NewProvider(hashFile)

	r := service.NewHandler(patternProvider, hashProvider)```

But I still get the error:

```/usr/local/go/pkg/tool/darwin_amd64/link: running clang++ failed: exit status 1
duplicate symbol '_fiftyoneDegreesSignalWait' in```

**Comment by stcharitak** [comment] 2021-02-15 16:41
Basically I want to be able to build a linux image from my mac using:
```
GO111MODULE=off CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
		go build -ldflags "$(LDFLAGS)" -o $(ARTIFACTS_DIR)/server-linux ./cmd/server
```
However, I get this error:
`building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format`

Could someone suggest a way so that I will be able to achieve that?

**Comment by ben51degrees** [comment] 2021-02-17 14:40
Hi @stcharitak,
I'll address these questions separately:

> However, I still get the redefined error if I use both algorithms in my program

This is because, in the V3 API, both Pattern and Hash have `threading.h/c` included. Meaning that both libraries contain the same definitions. In addition to that, they use some of the same structure names e.g. `fiftyoneDegreesDataSet`, so both cannot be compiled together into a single library.

In the V4 API, the naming supports compiling into a single libarary. Therefore, I don't believe there are plans to add support for this in V3.

>Basically I want to be able to build a linux image from my mac using

The arguments you supplied will build the pure Go source correctly for OSX, but the native C code will still be compiled using an OSX C compiler, and likely some OSX specific headers and libraries.
First you will need to define the C compiler by adding `CC=[compiler]`, replacing [compiler] with a suitable GCC cross-compiler. The same will need to happen with CXX to set the C++ compiler. You may also need to add some libararies to `LDFLAGS`.

I expect a Linux C compiler will need to be compiled manually on OSX, which is certainly non-trivial (though I'm happy to be proved wrong). So I'd suggest the simplest way is to use a Docker container to build. That way there's no cross-compilation required, and you can also use the container to run tests before deploying the app.

**Comment by stcharitak** [comment] 2021-02-17 15:04
Hi @ben51degrees ,

thanks a lot for your detailed response.

regarding the build of Linux image, I finally ended up using a Docker container to build as you suggested.

We mostly care about the fast response so we ended up using the hash algorithm only anyways. But I would like to know if there is a V4 lib that we can use? Take into account that we use only on-premise data files.

**Comment by ben51degrees** [comment] 2021-02-17 16:32
Hi @stcharitak,

Glad you got the build working.

Currently there is only V3 available for Go, for which you have access to the Enterprise datafiles. We can notify you directly once we have an established dev timeline for V4 and migrate you across accordingly.
